version: '3.8'

services:  
  n8n:  
    image: lunare/n8n-chinese
    container_name: n8n  
    restart: always  
    ports:  
      - "5678:5678"  
    volumes:  
      - ./n8n_data:/home/node/.n8n
    environment:  
      # 基本配置  
      - NODE_ENV=production  
      - N8N_HOST=yourdomain.com
      - N8N_RUNNERS_ENABLED=true
      - N8N_PORT=5678  
      - N8N_PROTOCOL=http  
      - WEBHOOK_URL=https://yourdomain.com
      - N8N_PROXY_HOPS=1
      - N8N_BASIC_AUTH_ACTIVE=true  
      - N8N_BASIC_AUTH_USER=n8nuser
      - N8N_BASIC_AUTH_PASSWORD=n8n_pass
      - N8N_ENCRYPTION_KEY=ab594a856b22f4624b0d965edb45358a783219493bcde50d9db4142e3ae187f8
      - GENERIC_TIMEZONE=Asia/Shanghai  
      - N8N_CONCURRENCY_PRODUCTION_LIMIT=5
      - N8N_LOG_LEVEL=info  
      - N8N_DEFAULT_LOCALE=zh-CN
      # PostgreSQL 数据库配置
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n_pass
      # 工作流历史配置  
      - N8N_WORKFLOW_HISTORY_ENABLED=true  
      - N8N_WORKFLOW_HISTORY_PRUNE_TIME=720  # 保留30天
      - N8N_SECURE_COOKIE=false
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: postgres_n8n
    restart: always
    environment:
      POSTGRES_DB: n8n
      POSTGRES_USER: n8n
      POSTGRES_PASSWORD: n8n_pass
    volumes:
      - ./postgres_data:/var/lib/postgresql/data